version: "3"
services:
  redis:
    image: "redis:alpine"
    container_name: redis
    environment:
      REDIS_REPLICATION_MODE: master
    ports:
     - "6379:6379"
​
  test_app:
    platform: linux/x86_64
    container_name: test_app
    build: ./
    ports:
      - "8000:8000"
    depends_on:
     - redis
